version: '3.7'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tutorial-phpmyadmin
    networks:
      - tutorial-backend
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
  backend:
    build: .
    image: tutorial-php/fpm:8.0.16
    container_name: tutorial-backend
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - ${APP_PORT}:80
    depends_on:
      - db
    command:
      >
        sh -i -c -e
        "
        composer install;
        php artisan migrate;
        php artisan serve --host 0.0.0.0 --port 80;
        "
    networks:
      - tutorial-backend
  db:
    image: mysql:8.0
    container_name: tutorial-mysql-db
    ports:
      - "${DB_DOCKER_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    healthcheck:
      test: "exit 0"
    networks:
      - tutorial-backend
    command: --default-authentication-plugin=mysql_native_password
networks:
  tutorial-backend:
